### ISSUE TITLE
Code action idea - generate alerts JSON

### ISSUE THREAD

**Issue by dlopes7** [dynatrace-extensions/dynatrace-extensions-copilot#43]
Similar to the dashboard generation feature, there should be a way for a user to generate a template alert from a metric definition.

Proposal:

* Code action on the `metrics` yaml element, not inside specific datasources
* User needs to input the file name and alert name
* The alert UUID should be based on the extension name and a counter

Example, extension `custom:my.snmp.extension`

The UUIDs always start with the same prefix, which should be a hash of the extension name.
The rest of the UUID should uniquely identify an alert definition for that prefix. ie, `0001`, `0002`, etc.

I think this is can help the user remain organized when creating/deleting/editing alerts.

Challenges:

* Things like `primaryDimensionKey` are hard to predict.
* If the user changes the UUID of an alert, the old alert still remains in Dynatrace.

**Comment by radu-stefan-dt** [comment]
I would say `metrics` yaml element might not be the best place for this.

I think it would be better if we create a separate Command that can be either triggered from the Command Palette to start a workflow. Let's say we call it `Create alert from metric` and it flows as such:
* `QuickPick` with all the metrics defined in `extension.yaml` for user to choose one
* Additional `QuickPick` or `InputBox` for any other choices or information we may want to request from the user (e.g. things that can't easily be deduced but the user should know)
* Command finalizes with:
  * `extension/alerts` folder created if needed
  * `alert-xxxx.json` file created inside it with the alert definition
  * `alerts` yaml element created/updated within `extension.yaml` based on what was created

I think this approach allows us more freedom in getting more info we might need for creating a good alert, but also we could then turn it into a `CodeAction`. So the `CodeAction` could be triggered on either the `alerts` yaml element and simply links to the Command. But also we may want to trigger on the `key` of a metric and pass the key as a parameter to the Command so that we skip the first step of the flow (i.e. selection of metric key).

Does this make sense? What do you think of this approach?
